name: "Build fast api and push to ecr"

on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - master

env: 
  REGION: us-east-1
  ECR_DOCKER_IMAGE: fast-api-repo

jobs:
  sonarqube:
    name: SonarQube Integration
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONAR_HOST_URL }}
        login: ${{ secrets.SONAR_TOKEN }}
        projectName: fastapi_project
        projectKey: realexcel2021_fastapi_project
  
  build-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
      

    steps:
      
      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src

      - uses: benjlevesque/short-sha@v3.0
        name: Get repo short sha
        id: short-sha
        with:
          length: 6


      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.REGION}}


      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
        

      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{secrets.ECR_DOCKER_IMAGE}}
          IMAGE_TAG: ${{ steps.short-sha.outputs.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_DOCKER_IMAGE:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_DOCKER_IMAGE:$IMAGE_TAG


        